name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential cmake clang \
          libunwind-dev \
          libgoogle-glog-dev \
          protobuf-compiler libprotobuf-dev \
          liblua5.3-dev \
          libeigen3-dev \
          libopencv-dev \
          libpcl-dev \
          libgtest-dev \
          portaudio19-dev \
          libsndfile1-dev \
          libportaudio2
      
      
